# Edit this file as needed. To cancel alerting on a field,
# comment out or delete its threshold entry.

alert_thresholds:
    num_err_log_entries: 0
    unsafe_shutdowns: 0
    percentage_used: 50
    media_errors: 0
    health_score: 90
    mean_temperature: 70 #Average of all sensor readings, in Celsius

alert_settings:
    alerts_enabled: true
    # See https://pypi.org/project/pytimeparse/ for possible values
    alert_interval: 1w # This regex is probably all you need: \d+m|\d+h|\d+d|\d+w
    # maximum number of emails that can be sent per hour (default 20)
    rate_limit: 20

LOG_FILE_NAME: /var/log/nvme_health.json